version: "3.8"

services:
  memcache:
    build: ./redis
    container_name: rd01
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 25s
      retries: 5

  api:
    depends_on:
      memcache:
        condition: service_healthy
    build: ./api
    container_name: api
    volumes:
      - assets:/api/assets

  web:
    depends_on:
      - api
    build: ./web
    container_name: web
    ports:
      - 3000:3000

  proxy:
    depends_on:
      - api
      - web
    build: ./nginx
    container_name: proxy
    ports:
      - 8000:8000

volumes:
  assets:
