version: "3.8"

services:
  memcache:
    build: ./redis
    container_name: rd01
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 25s
      retries: 5

  elastic:
    build: ./elastic
    container_name: es01
    healthcheck:
      test:
        ["CMD", "curl", "-f", "-u", "elastic:mrc201", "http://localhost:9200"]
      interval: 20s
      timeout: 30s
      retries: 1
    ports:
      - 9200:9200
      - 9300:9300

  api:
    depends_on:
      memcache:
        condition: service_healthy
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    container_name: api
    develop:
      watch:
        - action: sync
          path: ./api
          target: /api
          ignore:
            - main
        - action: rebuild
          path: ./api/go.mod
    volumes:
      - assets:/api/assets
    healthcheck:
      test: ["CMD", "go", "test", "./test"]
      interval: 1s
      timeout: 300s
      retries: 1

  web:
    depends_on:
      api:
        condition: service_healthy
      elastic:
        condition: service_healthy
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    container_name: web
    develop:
      watch:
        - action: sync
          path: ./web
          target: /web
          ignore:
            - node_modules/
        - action: rebuild
          path: ./web/package.json
    ports:
      - 3000:3000

  proxy:
    depends_on:
      - api
      - web
    build: ./nginx
    container_name: proxy
    ports:
      - 8000:8000

volumes:
  assets:
